---
title             : "How Journal Prestige affects Predicted and Actual Replication Success"
shorttitle        : "PREDICTING REPLICABILITY"

author: 
  - name          : "Lukas Röseler"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Fliednerstraße 21, 48149 Münster, Germany"
    email         : "lukas.roeseler@uni-muenster.de"
    
  - name          : "Jessica Röseler"
    affiliation   : "2"
    corresponding : no    # Define only one corresponding author
    address       : ""


affiliation:
  - id            : "1"
    institution   : "Münster Center for Open Science, University of Münster, Germany"
  - id            : "2"
    institution   : "Independent Researcher"

authornote: |
  This is a non-peer reviewed preprint. Data has not yet been collected and all results are place-holders. Both authors contributed equally. The order of the authors was determined by a game of Guess The Replication.

abstract: |
  With a large number of published research comes the need to efficiently assess research quality. Researchers have been relying on journal prestige, usually approximated by a journal's average number of citations. We investigated how researchers and non-researchers predict replication outcomes in the presence and absence of journals' impact factors. We compare this relation to the actual relationship between an open proxy for impact factor (OpenAlex mean citedness) and replication outcomes. For this, we used data from the FORRT Library of Reproduction and Replication Attempts (Wallrich et al., 2026) and a gamified paradigm "Guess The Replication" (GutheR). On a subset of N = 1,234 studies that were either successfully or not successfully replicated (mixed results and reproductions were excluded), higher mean citedness was  associated with a higher risk of replication failure but the relationship was too small to be practically relevant. Researchers [relied/did not rely] on mean citedness in their prediction. Higher mean citedness of the journal that published the original study were [not] associated with a higher probability of predicted success. This relationship was [different/similar] for non-researchers. We discuss the use of citation metrics as proxies for research quality.
  
  
  
keywords          : "replication, prediction market, impact factor, mean citedness, meta-science, bibliometrics"

bibliography      : ["guther-refs.bib","r-references.bib"]
appendix          :
  - "05_guther_supplement.Rmd"

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word
---

```{r setup, include = FALSE}

# This whole document is only here to initialize everything. It contains the settings
# for the manuscript, but nothing else.

# Set chunk options (i.e., how chunks will be handled globally, can however be overwritten locally in chunks)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed, 
                      echo=FALSE,     # chunks will not be printed in rendered document
                      include=FALSE,  # results will not be printed in the rendered document
                      message=FALSE,  # warnings and messages will no be printed in the rendered document
                      warning=FALSE)

# Seed for random number generation
set.seed(42)


```

```{r load-packages-data}

# Load packages
library(papaja)       # for generating the APA manuscript
library(tidyverse)    # for data analysis (and beautiful plots -> ggplot2)
library(prmisc)       # for printing stats
library(grateful)       # for citing r packages
library(openxlsx)       # to open Excel files
library(ggplot2)        # for plots
library(patchwork)      # to combine plots
# library(effectsize)   # for calculating effect sizes
# library(car)          # for calculating Levene's Test

# Load the data
# load("data/dataSCR.RData")

```

```{r child = c("01_guther_introduction.Rmd", "01b_guther_impactandreplicability.Rmd", "02_guther_methods.Rmd","03_guther_results.Rmd","04_guther_discussion.Rmd"), echo = FALSE}


```

\newpage

# (APPENDIX) Appendix {.unnumbered}

```{r child = "05_guther_supplement.Rmd"}
