```{r discussion}

# This file only contains the discussion

```

## Discussion

*Note: This document is part of the preregistration of the study. No
data has been collected for this project yet.*

Using an excerpt from the FORRT Library of Reproduction and Replication
Attempts, we measured the relationship between an open and reproducible
version of the OMC and collected data to
estimate the usage of this metric in predicting replication outcomes.
OMC and replicability were [unrelated / positively correlated /
negatively correlated]. Overall, participants [did not give higher or
lower / gave higher / gave lower] replicability scores to studies with a
high OMC. How OMC affected replicability ratings [differed / did not
differ] between different groups of participants. [explain difference if
present]

### Limitations

**Pseudo-prediction**: The most serious limitation of our study is that
participants did not predict replication outcome because outcomes were
already publicly available. Participants who knew about replication
studies could thus simply remember the outcomes. With over [400] studies
from various fields and replications sometimes being less visible less
cited than traditional research [@Hardwicke2021], we believe that this
problem is negligible overall.

**Selective sample**: For the simplicity of the design, we excluded
studies that had mixed findings, which were about 20% of the sample.

**Manipulation of OMC**: Hiding the journals' OMCs may not have
prevented researchers from relying on them if they knew the study or if
the journal that published the original study was already known to them.

**Open Source Alternative to Journal Impact Factor**: The values that we
presented - though highly correlated with the Clarivate JIF and more
transparent due to reliance on openly accessible data and reproducible -
may not be those that authors actually use though this is secondary to
the study's purpose.

**Hidden OMC does not prevent inference about OMC**: Researchers may
have been able to infer the journal or its OMC or JIF from the topic or
the quality.

**The limitations of FLoRA:** FLoRA limitations were inherited in this
project. For example, not all replications are indexed, replication
authors' success judgments are sometimes difficult to categorize when
authors could replicate one part but not another less important part.

**Survivorship bias**: The lives-mechanic introduces a survivorship
bias, wherein participants who make better predictions provide more
predictions.

**Deviations from the Preregistration**.

Table X lists how and why we deviated from the preregistration.

| Deviation | Justification | Effect on the Results |
|-----------|---------------|-----------------------|
|           |               |                       |
|           |               |                       |
|           |               |                       |

### Conclusion

-   [recommendation for research assessment]

## Acknowledgements

We thank participants from the Making Replications Count May Hackathon
2026 for valuable feedback during the creation of Guess the Replication

## Conflict of Interest and Funding

LR is the EiC of Replication Research, an open access journal supporting
replications and the managing director of the Münster Center for Open
Science, which has the purpose of supporting researchers in applying
open research techniques.

## Financial Support Statement

The authors report no financial support for this work.

## Ethics Statement

This study was approved by the Ethics Committee of the Department of
Psychology, University of Münster on 9 April 2026, protocol number
2026-22-LR.

## Data Availability

The datasets (i.e., FLoRA data as of 24 April, 2026) used for this study
are available on the OSF (<https://osf.io/ku8xm/overview>). The
up-to-date version of FLoRA is available at
<https://github.com/forrtproject/FReD-data/blob/main/output/flora.csv>.

## Declaration of AI Use

Gemini 3.1 Pro Preview, Claude 4.6 Sonnett, and Claude 4.7 Opus were
used to create Guess the Replication, to complement a manual literature
search on prediction markets, to revise r-scripts, and to proof-read
written texts.

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

::: {#refs custom-style="Bibliography"}
:::

\endgroup
